
package co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IServiceFuncionarioService", targetNamespace = "http://funcionario.business.colfondos.com.co/", wsdlLocation = "http://172.18.160.212:63110/Funcionario?wsdl")
public class IServiceFuncionarioService
    extends Service
{

    private final static URL ISERVICEFUNCIONARIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISERVICEFUNCIONARIOSERVICE_EXCEPTION;
    private final static QName ISERVICEFUNCIONARIOSERVICE_QNAME = new QName("http://funcionario.business.colfondos.com.co/", "IServiceFuncionarioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.18.160.212:63110/Funcionario?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISERVICEFUNCIONARIOSERVICE_WSDL_LOCATION = url;
        ISERVICEFUNCIONARIOSERVICE_EXCEPTION = e;
    }

    public IServiceFuncionarioService() {
        super(__getWsdlLocation(), ISERVICEFUNCIONARIOSERVICE_QNAME);
    }

    public IServiceFuncionarioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISERVICEFUNCIONARIOSERVICE_QNAME, features);
    }

    public IServiceFuncionarioService(URL wsdlLocation) {
        super(wsdlLocation, ISERVICEFUNCIONARIOSERVICE_QNAME);
    }

    public IServiceFuncionarioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISERVICEFUNCIONARIOSERVICE_QNAME, features);
    }

    public IServiceFuncionarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceFuncionarioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServiceFuncionario
     */
    @WebEndpoint(name = "IServiceFuncionarioPort")
    public IServiceFuncionario getIServiceFuncionarioPort() {
        return super.getPort(new QName("http://funcionario.business.colfondos.com.co/", "IServiceFuncionarioPort"), IServiceFuncionario.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServiceFuncionario
     */
    @WebEndpoint(name = "IServiceFuncionarioPort")
    public IServiceFuncionario getIServiceFuncionarioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://funcionario.business.colfondos.com.co/", "IServiceFuncionarioPort"), IServiceFuncionario.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISERVICEFUNCIONARIOSERVICE_EXCEPTION!= null) {
            throw ISERVICEFUNCIONARIOSERVICE_EXCEPTION;
        }
        return ISERVICEFUNCIONARIOSERVICE_WSDL_LOCATION;
    }

}
