
package co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceFuncionario", targetNamespace = "http://funcionario.business.colfondos.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServiceFuncionario {


    /**
     * 
     * @param consultarEdadPensionSimpleRequest
     * @return
     *     returns co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario.ConsultarEdadPensionSimpleResponse
     * @throws InternalException
     */
    @WebMethod
    @WebResult(name = "ConsultarEdadPensionSimpleResponse", targetNamespace = "")
    @RequestWrapper(localName = "consultarEdadPension", targetNamespace = "http://funcionario.business.colfondos.com.co/", className = "co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario.ConsultarEdadPension")
    @ResponseWrapper(localName = "consultarEdadPensionResponse", targetNamespace = "http://funcionario.business.colfondos.com.co/", className = "co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario.ConsultarEdadPensionResponse")
    public ConsultarEdadPensionSimpleResponse consultarEdadPension(
        @WebParam(name = "ConsultarEdadPensionSimpleRequest", targetNamespace = "")
        ConsultarEdadPensionSimpleRequest consultarEdadPensionSimpleRequest)
        throws InternalException
    ;

    /**
     * 
     * @param consultarParametrosHerramientasFVSimpleRequest
     * @return
     *     returns co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario.ResponseConsultarParametrosHerramientasFV
     * @throws InternalException
     */
    @WebMethod
    @WebResult(name = "ResponseConsultarParametrosHerramientasFV", targetNamespace = "")
    @RequestWrapper(localName = "consultarParametrosHerramientasFV", targetNamespace = "http://funcionario.business.colfondos.com.co/", className = "co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario.ConsultarParametrosHerramientasFV")
    @ResponseWrapper(localName = "consultarParametrosHerramientasFVResponse", targetNamespace = "http://funcionario.business.colfondos.com.co/", className = "co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario.ConsultarParametrosHerramientasFVResponse")
    public ResponseConsultarParametrosHerramientasFV consultarParametrosHerramientasFV(
        @WebParam(name = "ConsultarParametrosHerramientasFVSimpleRequest", targetNamespace = "")
        ConsultarParametrosHerramientasFVSimpleRequest consultarParametrosHerramientasFVSimpleRequest)
        throws InternalException
    ;

    /**
     * 
     * @param consultarSalarioMinRequest
     * @return
     *     returns co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario.SalariosMinimos
     * @throws InternalException
     */
    @WebMethod
    @WebResult(name = "ConsultarSalarioMinResponse", targetNamespace = "")
    @RequestWrapper(localName = "consultarSalarioMinimo", targetNamespace = "http://funcionario.business.colfondos.com.co/", className = "co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario.ConsultarSalarioMinimo")
    @ResponseWrapper(localName = "consultarSalarioMinimoResponse", targetNamespace = "http://funcionario.business.colfondos.com.co/", className = "co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario.ConsultarSalarioMinimoResponse")
    public SalariosMinimos consultarSalarioMinimo(
        @WebParam(name = "ConsultarSalarioMinRequest", targetNamespace = "")
        ConsultarSalarioMinimoRequest consultarSalarioMinRequest)
        throws InternalException
    ;

    /**
     * 
     * @param consultarRentaPortafolioRequest
     * @return
     *     returns co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario.ResponseConsultarRentaPortafolio
     * @throws InternalException
     */
    @WebMethod
    @WebResult(name = "ResponseConsultarRentaPortafolio", targetNamespace = "")
    @RequestWrapper(localName = "consultarRentaPortafolio", targetNamespace = "http://funcionario.business.colfondos.com.co/", className = "co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario.ConsultarRentaPortafolio")
    @ResponseWrapper(localName = "consultarRentaPortafolioResponse", targetNamespace = "http://funcionario.business.colfondos.com.co/", className = "co.com.colfondos.tech.ws.cliente.funcionario.service_funcionario.ConsultarRentaPortafolioResponse")
    public ResponseConsultarRentaPortafolio consultarRentaPortafolio(
        @WebParam(name = "ConsultarRentaPortafolioRequest", targetNamespace = "")
        ConsultarRentaPortafolioRequest consultarRentaPortafolioRequest)
        throws InternalException
    ;

}
